// <auto-generated />
using INTEX.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INTEX.API.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("INTEX.API.Data.Movie", b =>
                {
                    b.Property<int>("show_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adventure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anime_Series_International_TV_Shows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("British_TV_Shows_Docuseries_International_TV_Shows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Children")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comedies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comedies_Dramas_International_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comedies_International_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comedies_Romantic_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crime_TV_Shows_Docuseries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Documentaries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Documentaries_International_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Docuseries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dramas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dramas_International_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dramas_Romantic_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Family_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fantasy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horror_Movies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("International_Movies_Thrillers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("International_TV_Shows_Romantic_TV_Shows_TV_Dramas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kids_TV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Language_TV_Shows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Musicals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nature_TV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reality_TV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spirituality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_Action")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_Comedies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TV_Dramas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Talk_Shows_TV_Comedies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Thrillers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("release_year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("show_id");

                    b.ToTable("movies_titles");
                });
#pragma warning restore 612, 618
        }
    }
}
