export interface Movie {
  showId: string;
  type: string;
  title: string;
  director: string | null;
  cast: string | null;
  country: string | null;
  releaseYear: number;
  rating: string | null;
  duration: string | null;
  description: string | null;
  posterUrl: string | null;
  averageStarRating?: number;
  action: number;
  adventure: number;
  animeSeriesInternationalTVShows: number;
  britishTVShowsDocuseriesInternationalTVShows: number;
  children: number;
  comedies: number;
  comediesDramasInternationalMovies: number;
  comediesInternationalMovies: number;
  comediesRomanticMovies: number;
  crimeTVShowsDocuseries: number;
  documentaries: number;
  documentariesInternationalMovies: number;
  docuseries: number;
  dramas: number;
  dramasInternationalMovies: number;
  dramasRomanticMovies: number;
  familyMovies: number;
  fantasy: number;
  horrorMovies: number;
  internationalMoviesThrillers: number;
  internationalTVShowsRomanticTVShowsTVDramas: number;
  kidsTV: number;
  languageTVShows: number;
  musicals: number;
  natureTV: number;
  realityTV: number;
  spirituality: number;
  tVAction: number;
  tVComedies: number;
  tVDramas: number;
  talkShowsTVComedies: number;
  thrillers: number;
}
