export const GENRE_MAPPING: { [key: string]: string } = {
  'Action': 'action',
  'Adventure': 'adventure',
  'Anime Series': 'animeSeriesInternationalTVShows',
  'British TV Shows': 'britishTVShowsDocuseriesInternationalTVShows',
  'Children': 'children',
  'Comedies': 'comedies',
  'Comedy Dramas': 'comediesDramasInternationalMovies',
  'Comedy International': 'comediesInternationalMovies',
  'Comedy Romance': 'comediesRomanticMovies',
  'Crime TV Shows': 'crimeTVShowsDocuseries',
  'Documentaries': 'documentaries',
  'Documentary International': 'documentariesInternationalMovies',
  'Docuseries': 'docuseries',
  'Dramas': 'dramas',
  'Drama International': 'dramasInternationalMovies',
  'Drama Romance': 'dramasRomanticMovies',
  'Family': 'familyMovies',
  'Fantasy': 'fantasy',
  'Horror': 'horrorMovies',
  'International Thrillers': 'internationalMoviesThrillers',
  'International TV Shows': 'internationalTVShowsRomanticTVShowsTVDramas',
  'Kids TV': 'kidsTV',
  'Language TV Shows': 'languageTVShows',
  'Musicals': 'musicals',
  'Nature TV': 'natureTV',
  'Reality TV': 'realityTV',
  'Spirituality': 'spirituality',
  'TV Action': 'tVAction',
  'TV Comedies': 'tVComedies',
  'TV Dramas': 'tVDramas',
  'Talk Shows': 'talkShowsTVComedies',
  'Thrillers': 'thrillers'
};

export const AVAILABLE_GENRES = Object.keys(GENRE_MAPPING); 